name: 'terraform validate'

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run:  terraform init
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      shell: bash