name: 'terraform plan'

runs:
  using: composite
  steps:
    - name: Terraform Init
      run: terraform init
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      shell: bash

    - name: Terraform Plan
      run: terraform plan
      shell: bash