name: 'terraform validate'

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Terraform Init
      run: terraform init
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      shell: bash

    - name: Terraform Plan
      run: terraform plan
      shell: bash