name: 'terraform validate'

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Setup AWS Credentials
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      shell: bash

    - name: Terraform Init
      run: terraform init
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      shell: bash

    - name: Terraform Plan
      run: terraform plan
      shell: bash