name: Pull Request Workflow (develop)

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**/*.tf'

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Validate
        uses: ./.github/actions/validate

      - name: Terraform Plan
        uses: ./.github/actions/plan