name: Pull Request Workflow (develop)

on:
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '**/*.tf'

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Validate
        uses: ./.github/actions/validate

      - name: Test Send Email
        run: |
          sudo chmod +x ./email_setup.sh
          ./email_setup.sh $GMAIL_USERNAME $GMAIL_PASSWORD
