name: Pull Request Workflow (develop)

on:
  pull_request:
    branches:
      - develop

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Validate
        uses: ./.github/actions/validate